version: 2
services:
  web:
    image: railwayapp/golang:1.20
    env:
      - DBHOST=${MYSQLHOST}
      - DBPORT=${MYSQLPORT}
      - DBUSER=${MYSQLUSER}
      - DBPASS=${MYSQLPASSWORD}
      - DBNAME=${MYSQLDATABASE}
    command: go run main.go
