version: 2
services:
  web:
    image: railwayapp/golang:1.20
    env:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: go run main.go
  db:
    image: mysql:8
    ports:
      - 3306
